# permissions for end users to view ilmpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ilmpolicy-viewer-role
rules:
- apiGroups:
  - elasticsearch.my.domain
  resources:
  - ilmpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticsearch.my.domain
  resources:
  - ilmpolicies/status
  verbs:
  - get
