# permissions for end users to edit ilmpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ilmpolicy-editor-role
rules:
- apiGroups:
  - elasticsearch.my.domain
  resources:
  - ilmpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.my.domain
  resources:
  - ilmpolicies/status
  verbs:
  - get
